// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QBLockService.Data;

#nullable disable

namespace QBLockService.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("QBLockService.Models.ActiveLock", b =>
        {
            b.Property<string>("LockId").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTime>("AcquiredAtUtc").HasColumnType("TEXT");
            b.Property<string>("AppInstanceId").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("DisplayName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Email").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("FileKey").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("TEXT");
            b.Property<DateTime>("LastHeartbeatUtc").HasColumnType("TEXT");
            b.Property<string>("LocalPath").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("MachineName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime?>("ReleasedAtUtc").HasColumnType("TEXT");
            b.Property<string>("ReleasedReason").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
            b.Property<string>("UserName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.HasKey("LockId");
            b.HasIndex("FileKey").IsUnique().HasFilter("[Status] = 'Active'").HasDatabaseName("UQ_ActiveLocks_FileKey_Active");
            b.ToTable("ActiveLocks");
        });

        modelBuilder.Entity("QBLockService.Models.AuditLog", b =>
        {
            b.Property<long>("AuditId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("AppInstanceId").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Details").HasColumnType("TEXT");
            b.Property<string>("EventType").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("FileKey").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("FileName").HasMaxLength(260).HasColumnType("TEXT");
            b.Property<string>("LockId").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("MachineName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("TimestampUtc").HasColumnType("TEXT");
            b.Property<string>("UserName").HasMaxLength(200).HasColumnType("TEXT");
            b.HasKey("AuditId");
            b.HasIndex("TimestampUtc");
            b.HasIndex("FileKey");
            b.ToTable("AuditLogs");
        });
#pragma warning restore 612, 618
    }
}
